//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibraryProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCase
    {
        public int CaseId { get; set; }
        public string CaseMonth { get; set; }
        public Nullable<decimal> CaseTotal { get; set; }
    }
}
